### ISSUE TITLE
Cannot install `geosx_xml_tools` on Pecan

### ISSUE THREAD

**Issue by jhuang2601** [GEOSX/GEOSX#1722]
I encountered some problem in installing `geosx_xml_tools` on Pecan:
```
[j0551570@rdhpc-n4 build-pecan_cpu2-release]$ make geosx_xml_tools
Generating ../../bin/preprocess_xml, ../../bin/format_xml
/usr/bin/python
Using an existing python installation...
Error: the target python environment must have virtualenv installed!
make[3]: *** [bin/preprocess_xml] Error 1
make[2]: *** [coreComponents/python/CMakeFiles/geosx_xml_tools.dir/all] Error 2
make[1]: *** [coreComponents/python/CMakeFiles/geosx_xml_tools.dir/rule] Error 2
make: *** [geosx_xml_tools] Error 2
```
and also failed to install the required virtualenv:
```
[j0551570@rdhpc-n4 build-pecan_cpu2-release]$ pip install virtualenv
Collecting virtualenv
  Using cached https://files.pythonhosted.org/packages/ef/a1/4e1700f25211b3851e6be6675061e0c8eae7585d80177a40e9b02d1105d8/virtualenv-20.13.0-py2.py3-none-any.whl
Collecting importlib-metadata>=0.12; python_version < "3.8" (from virtualenv)
  Using cached https://files.pythonhosted.org/packages/50/05/fef7fbb7e781e0632ebba4e6e37bcc88b9615e76338850dc31435091ddc0/importlib_metadata-4.10.0.tar.gz
  Running setup.py (path:/tmp/pip-build-tRCnIH/importlib-metadata/setup.py) egg_info for package importlib-metadata produced metadata for project name unknown. Fix your #egg=importlib-metadata fragments.
Requirement already satisfied (use --upgrade to upgrade): six<2,>=1.9.0 in /usr/lib/python2.7/site-packages (from virtualenv)
Collecting platformdirs<3,>=2 (from virtualenv)
  Using cached https://files.pythonhosted.org/packages/be/00/bd080024010e1652de653bd61181e2dfdbef5fa73bfd32fec4c808991c31/platformdirs-2.4.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-tRCnIH/platformdirs/setup.py", line 1
        from __future__ import annotations
    SyntaxError: future feature annotations is not defined
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-tRCnIH/platformdirs/
You are using pip version 8.1.2, however version 21.3.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
```
One more concern, using `make all` did not compile the `geosx_xml_tools`, which should be fixed.

**Comment by cssherman** [comment]
@jhuang2601 - that's a very old version of pip, so that may be the issue (try the recommended `pip install --upgrade pip`)  Also, make sure that you have write permissions for the python distribution.

As the pygeosx build becomes more used, we'll end up installing the tools in the that environment (and not the one specified in the cmake or used to configure GEOSX)

**Comment by jhuang2601** [comment]
By changing to `PYTHON_ROOT=/home/j0551570/.conda/envs/py2/python` in `setupVirtualPythonEnvironment.bash` , now `virtualenv` can be installed and `make geosx_xml_tools` can be running
```
(py2) [j0551570@rdhpc-n4 build-pecan_cpu2-release]$ make geosx_xml_tools
Scanning dependencies of target geosx_xml_tools
Generating ../../bin/preprocess_xml, ../../bin/format_xml
/home/j0551570/.conda/envs/py2/bin/python
Using an existing python installation...
Creating a virtual python environment...
created virtual environment CPython2.7.18.final.0-64 in 2274ms
  creator CPython2Posix(dest=/lustre4/scratch/j0551570/geosx/HFSolver/GEOSX/build-pecan_cpu2-release/python/geosx, clear=False, no_vcs_ignore=False, global=True)
  seeder FromAppData(download=False, pip=bundle, wheel=bundle, setuptools=bundle, via=copy, app_data_dir=/home/j0551570/.local/share/virtualenv)
    added seed packages: pip==20.3.4, setuptools==44.1.1, wheel==0.37.1
  activators NushellActivator,PythonActivator,FishActivator,CShellActivator,PowerShellActivator,BashActivator
Writing a startup script to /lustre4/scratch/j0551570/geosx/HFSolver/GEOSX/build-pecan_cpu2-release/python/start_geosx.sh
Installing packages...
Traceback (most recent call last):
  File "/lustre4/scratch/j0551570/geosx/HFSolver/GEOSX/build-pecan_cpu2-release/python/geosx/bin/pip", line 5, in <module>
    from pip._internal.cli.main import main
ImportError: No module named _internal.cli.main
Traceback (most recent call last):
  File "/lustre4/scratch/j0551570/geosx/HFSolver/GEOSX/build-pecan_cpu2-release/python/geosx/bin/pip", line 5, in <module>
    from pip._internal.cli.main import main
ImportError: No module named _internal.cli.main
Complete!

Notes:
To load the virtual environment, run:
  source /lustre4/scratch/j0551570/geosx/HFSolver/GEOSX/build-pecan_cpu2-release/python/start_geosx.sh
To exit the environent, run:
  deactivate
Built target geosx_xml_tools
```
However, `make geosx` failed
```
make[2]: Target `CMakeFiles/geosx.dir/all' not remade because of errors.
make[1]: *** [CMakeFiles/geosx.dir/rule] Error 2
make[1]: Target `geosx' not remade because of errors.
make: *** [geosx] Error 2
```
These errors happened after
```
[j0551570@rdhpc-n2 GEOSX]$ module load anaconda3
[j0551570@rdhpc-n2 GEOSX]$ source activate py2
```
Without using py2, there is no issue on `make geosx`. 

I can install `virtualenv` under `conda` and run `make geosx_xml_tool`s , but not `make geosx`.
Without using `anaconda3`, I can `make geosx` , but cannot install `virtualenv`.
I'm struggling to find a solution to do both (`make geosx` and `make geosx_xml_tools`).

**Comment by jhuang2601** [comment]
> @jhuang2601 - that's a very old version of pip, so that may be the issue (try the recommended `pip install --upgrade pip`) Also, make sure that you have write permissions for the python distribution.
> 
> As the pygeosx build becomes more used, we'll end up installing the tools in the that environment (and not the one specified in the cmake or used to configure GEOSX)

also tried to upgrade pip but no success
```
[j0551570@rdhpc-n4 ~]$ pip install --upgrade pip
Cache entry deserialization failed, entry ignored
Collecting pip
  Using cached https://files.pythonhosted.org/packages/da/f6/c83229dcc3635cdeb51874184241a9508ada15d8baa337a41093fab58011/pip-21.3.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-Yx5LKC/pip/setup.py", line 7
        def read(rel_path: str) -> str:
                         ^
    SyntaxError: invalid syntax
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-Yx5LKC/pip/
You are using pip version 8.1.2, however version 21.3.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
```

**Comment by TotoGaz** [comment]
@jhuang2601 this looks like a python version error. This type hint `def read(rel_path: str) -> str:` syntax is for more recent versions. Maybe `pip` is related to `python2`?

**Comment by cssherman** [comment]
Also, changing the version of the python in the script  shouldn't affect the rest of the build.  And yes, all of the python tools in the repo are python3 (and still should be python2) compatible

**Comment by cssherman** [comment]
@jhuang2601 - the easiest thing to do here is to re-run the GEOSX `scripts/config-build.py ` step with the version of python that seems to be working.  When you re-compile the code, `geosx_xml_tools` should be installed correctly, and you will likely avoid the other error you seemed to encounter

**Comment by cssherman** [comment]
(The current default behavior is to use the version used in the configuration to build the virtual environment and geosx_xml_tools, in case that was unclear)

**Comment by jhuang2601** [comment]
> @jhuang2601 - the easiest thing to do here is to re-run the GEOSX `scripts/config-build.py ` step with the version of python that seems to be working. When you re-compile the code, `geosx_xml_tools` should be installed correctly, and you will likely avoid the other error you seemed to encounter

@cssherman I've tested it and reported the issue of `make geosx`
```
eSystem/MultiphaseSystemProperties/FactorMultiphaseSystemProperties.cpp.o                                              
/lustre4/scratch/j0551570/geosx/HFSolver/GEOSX/src/coreComponents/fileIO/coupling/hdf5_interface/coupler.cpp: In function 'void writeBoundaryFile(MPI_Comm, const char*, double, const bool*, int64_t&, int64_t&, int64_t, const int64_t*, const FieldMap_in&, int64_t&, int64_t&, int64_t, const FieldMap_in&)':
/lustre4/scratch/j0551570/geosx/HFSolver/GEOSX/src/coreComponents/fileIO/coupling/hdf5_interface/coupler.cpp:296:5: error: 'H5Pset_fapl_mpio' was not declared in this scope; did you mean 'H5Pset_fapl_stdio'?
  296 |     H5Pset_fapl_mpio( file_access, comm, MPI_INFO_NULL );
      |     ^~~~~~~~~~~~~~~~
      |     H5Pset_fapl_stdio
/lustre4/scratch/j0551570/geosx/HFSolver/GEOSX/src/coreComponents/fileIO/coupling/hdf5_interface/coupler.cpp: In function 'void readBoundaryHeader(MPI_Comm, const char*, double&, int64_t&, int64_t&)':
/lustre4/scratch/j0551570/geosx/HFSolver/GEOSX/src/coreComponents/fileIO/coupling/hdf5_interface/coupler.cpp:455:5: error: 'H5Pset_fapl_mpio' was not declared in this scope; did you mean 'H5Pset_fapl_stdio'?
  455 |     H5Pset_fapl_mpio( file_access, comm, MPI_INFO_NULL );
      |     ^~~~~~~~~~~~~~~~
      |     H5Pset_fapl_stdio
/lustre4/scratch/j0551570/geosx/HFSolver/GEOSX/src/coreComponents/fileIO/coupling/hdf5_interface/coupler.cpp: In function 'void readBoundaryFile(MPI_Comm, const char*, int64_t, int64_t, int64_t, FieldMap_out&, int64_t, int64_t, int64_t, FieldMap_out&)':
/lustre4/scratch/j0551570/geosx/HFSolver/GEOSX/src/coreComponents/fileIO/coupling/hdf5_interface/coupler.cpp:497:5: error: 'H5Pset_fapl_mpio' was not declared in this scope; did you mean 'H5Pset_fapl_stdio'?
  497 |     H5Pset_fapl_mpio( file_access, comm, MPI_INFO_NULL );
      |     ^~~~~~~~~~~~~~~~
      |     H5Pset_fapl_stdio
make[3]: *** [coreComponents/fileIO/coupling/hdf5_interface/CMakeFiles/hdf5_interface.dir/coupler.cpp.o] Error 1
make[3]: Target `coreComponents/fileIO/coupling/hdf5_interface/CMakeFiles/hdf5_interface.dir/build' not remade because of errors.
make[2]: *** [coreComponents/fileIO/coupling/hdf5_interface/CMakeFiles/hdf5_interface.dir/all] Error 2
```

**Comment by cssherman** [comment]
@jhuang2601 - that doesn't look good.  As long as the configuration step completes, the version of python you used shouldn't have any impact on the (non-python tool) part of the build...  Are you building with the current version of develop?

**Comment by TotoGaz** [comment]
I've checked with @jhuang2601 and what is happening is that when loading `module load anaconda3`, there is some kind of conflict with the `hdf5` provided by `anaconda`.

Running the compilation with the `-E` option shows that
```
:# 1 "/hrtc/apps/scripting/anaconda3/x86_64/2020.02/include/hdf5.h" 1
```
is not the `hdf5.h` from the TPLs. But the `config-build.py` selects the correct one!
```
-- HDF5_DIR_REAL=/.../travis-deployments/CPU/GEOSX_TPL-a634fc6/hdf5
-- Checking that found HDF5_INCLUDE_DIRS are in HDF5_DIR
-- HDF5_INCLUDE_DIRS=/.../travis-deployments/CPU/GEOSX_TPL-a634fc6/hdf5/include
--  /.../travis-deployments/CPU/GEOSX_TPL-a634fc6/hdf5/include includes HDF5_DIR (/.../travis-deployments/CPU/GEOSX_TPL-a634fc6/hdf5)
```
Unloading `anaconda` solves the issue.

Any idea why our build gets bypassed like that?

**Comment by TotoGaz** [comment]
Closing in favor of https://github.com/GEOSX/GEOSX/issues/1738
